### ISSUE TITLE
Incompetence

### ISSUE THREAD

**Issue by kekkodance** [Wamy-Dev/ReziWebsite#12]
This tool is just a scraper for malicious/plain bad game sites, hidden under a fancy closed source UI on a site.
You give an entire story and even made an API for the scraper, making it "simple" for people of any level to catch malware.
You should spens your expertise with UI on making actually useful resources instead of making a free advertisement to sites like SteamRip, which download games from dubious sources in the beginning and regurgitate the installed files into a badly compressed RAR file.

Almost no source you scrape is widely accepted by the community. You could have also consolidated both of your scrapers (same code, different py files for scraping tho) into a single site instead of buying two domains and giving another story for why it's called that way.

Another plain giveaway that this is just doomed is your constant mention of HEY! FREE SHIT! PIRACY! HERE! NOW! instead of giving subtle hints which don't set off alarms. I am giving you these tips because you seem to have a geniune interest in UI/UX and don't want your site to link to bad shit.

Another suggestion is to tweak your scrapers to not actually spam the sites with request/do it more efficiently, as scraping is generally bad and unethical. Use APIs when possible.

**Comment by Wamy-Dev** [comment]
I am almost convinced this is a troll post and am quite close to deleting the issue. 

You claim that SteamRip is a bad site, but it is listed in r/piracy's megathread. If it is listed there for thousands, it's good enough for my website -> [Link to megathread](https://rentry.co/megathread-games#steamrip). As well as r/Piracy's megathread it is in the FMHY megathread as well, with a big ol star meaning that people should check SteamRip first before anything else [Link to megathread](https://fmhy.pages.dev/gamingpiracyguide/)

> Almost no source you scrape is widely accepted by the community.

You are obviously in a different community because every single one of those sources can be found in both/either of r/Piracy's Megathread and in the FMHY Megathread. Again, if it is good enough to put into a list for thousands, it's good enough for my search engine for thousands. 

> Another plain giveaway that this is just doomed is your constant mention of HEY! FREE SHIT! PIRACY! HERE! NOW!

I have never said those words ever and I don't think it is really conveyed like that through my website or any of my posts. If you feel that way, everyone is entitled to an opinion no matter how wrong it is. And I have no idea what these "subtle hints which don't set off alarms" are.

My site does not link to any malicious sites and through my experience and also from the use of hundreds of people every single day on my site, nobody has said anything about Malware, which is nonexistent on these sites anyways. I give a proper warning in my about page about Ads and Adblockers and how to utilize them to stay safe on these sites, which most have ads on, which may give you malware if you click on it. But that is up to the user, not me.

> Another suggestion is to tweak your scrapers to not actually spam the sites with request/do it more efficiently

Finally something that actually makes sense. I know the ethics of scraping and I realize that it's not great, but most of these sites are hosted on page builders like WordPress where they don't have an API to get their data. It is all Server Side Rendered which means that what I see is what I get. They might be using an API internally but I can't see those requests which also means that I can't use it. Scrapy is good about keeping it ethical. I do present myself with a UserAgent which is about the most I can do in this situation. Besides, its a trade. I scrape their site and send hundreds of requests in less than a hour, but in return, they get free advertisement, which is why none of them have blocked me or contacted me personally about it. 



Either way, basically nothing you have said has any meaning, and the only reason I have responded to such an issue is so that people who may have the same concerns can see this and understand a little bit more about the site. Thank you.
