### ISSUE TITLE
Spallmasons missing

### ISSUE THREAD

**Issue by ozne1** [Wamy-Dev/ReziWebsite#16]
https://store.steampowered.com/app/1618380/Spellmasons/

**Comment by Wamy-Dev** [comment]
It looks like this hasn't been cracked yet. Some smaller titles such as this one may never be cracked and won't be added to Rezi due to that fact.

**Don't be tempted to download this from anywhere other than Steam or wherever else it is sold.** 

A quick search showed that only IGG-GAMES and some other sketchy sites have downloads, which means that it isn't actually cracked. Don't download from these sites.

It's not even listed on CS.RIN.RU, so *please please please* don't download it from anywhere. For now I will leave this closed, but if it pops up on CS.RIN.RU, it'll be added to Rezi.
