### ISSUE TITLE
Searching specifics sometimes doesn’t bring up the results

### ISSUE THREAD

**Issue by Nexxol** [Wamy-Dev/ReziWebsite#6]
I noticed an odd behaviour where when I searched “Super Mario 64” I got most games that had Super Mario/Mario/super in the title but super Mario 64 was nowhere to be seen. But when I searched “Mario 64” it was there despite the game result having the title “super Mario 64” only “mario 64” found it and not the actual title “super mario 64” 

I was also only able to find super Mario 64 on page 7 by searching “Mario 64” when it should’ve been on the first page

**Comment by Wamy-Dev** [comment]
This is likely due to the Meilisearch settings I have put up and how it gets the closest items to the search. Because console comes in first priority, typing "super", brings up "SNES" and then the search tries to do the rest. Same with "64", brings up "Nintendo 64". Thanks for sharing, Ill work on it.

**Comment by Wamy-Dev** [comment]
Please try it again, I have altered the settings of how searches are done. Seems to work pretty well for me. I tried `n64 super mario 64` and `super mario 64`  it worked perfectly with Super Mario 64 coming first. 
![image](https://user-images.githubusercontent.com/25761442/211229641-c6a8df6a-039c-4fb7-a6e0-285028156c0e.png)

**Comment by Nexxol** [comment]
Works perfectly, thank you! The issue also applied to stuff like “Super Mario Galaxy” but now it comes up on the first page
